name: chatrio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flutter:
    sdk: flutter
  go_router: ^16.2.0
  path: ^1.9.1
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/