// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPzFjTI0hdTsCJ938dSXaNdANTsR8oFU',
    appId: '1:939007904042:web:e18d4704e17c58947d3653',
    messagingSenderId: '939007904042',
    projectId: 'chatrio-708e2',
    authDomain: 'chatrio-708e2.firebaseapp.com',
    databaseURL: 'https://chatrio-708e2-default-rtdb.firebaseio.com',
    storageBucket: 'chatrio-708e2.firebasestorage.app',
    measurementId: 'G-BRT5RBYX61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5UTCmPd-JQ5M8WYQkB1_J0En66jWJZs',
    appId: '1:939007904042:android:5d03a9b29cb104497d3653',
    messagingSenderId: '939007904042',
    projectId: 'chatrio-708e2',
    databaseURL: 'https://chatrio-708e2-default-rtdb.firebaseio.com',
    storageBucket: 'chatrio-708e2.firebasestorage.app',
  );
}
